# automatically generated by the FlatBuffers compiler, do not modify

# namespace: graphpipe

import flatbuffers

class InferResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInferResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InferResponse()
        x.Init(buf, n + offset)
        return x

    # InferResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InferResponse
    def OutputTensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferResponse
    def OutputTensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InferResponse
    def Errors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Error import Error
            obj = Error()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InferResponse
    def ErrorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def InferResponseStart(builder): builder.StartObject(2)
def InferResponseAddOutputTensors(builder, outputTensors): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(outputTensors), 0)
def InferResponseStartOutputTensorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def InferResponseAddErrors(builder, errors): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(errors), 0)
def InferResponseStartErrorsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def InferResponseEnd(builder): return builder.EndObject()
