# automatically generated by the FlatBuffers compiler, do not modify

# namespace: graphpipe

class Type(object):
    Null = 0
    Uint8 = 1
    Int8 = 2
    Uint16 = 3
    Int16 = 4
    Uint32 = 5
    Int32 = 6
    Uint64 = 7
    Int64 = 8
    Float16 = 9
    Float32 = 10
    Float64 = 11
    String = 12

